project/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url('^hello/', views.hello)
]

project/detail/urls.py
from django.conf.urls import url
from detail import views


urlpatterns = [
    url(r'^detail/(\d+)/', views.detail),
    url(r'^collect/', views.collect),
]

project/project/urls.py
from django.conf.urls import url, include
from django.views.static import serve

from project import settings

urlpatterns = [
    url(r'^app/', include('app.urls')),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),  # 配置这个用来DEBUG等于False的时候可以加载静态文件
    url(r'kaiapp/', include('kaiapp.urls', namespace='kaiapp')),
    url(r'^detail/', include('detail.urls')),
    url(r'^cwd/', include('cwdapp.urls')),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),  # 配置这个用来DEBUG等于False的时候可以加载静态文件
    # url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # 配置这个用来DEBUG等于False的时候去加载静态图片
    # url(r'^$', views.home),  # 通过空匹配返回首页
    url(r'^xym/', include(('xym.urls', 'xym'), namespace='xym')),
]

from django.contrib.staticfiles.urls import static
from project import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/xym/urls.py
from django.conf.urls import url

from xym import views


urlpatterns = [
    # url('^hello/', views.hello)
    #首页
    # url(r'^index/',views.my_home,name='my_index'),
    # #登录
    url(r'^login/',views.login,name='login'),
    # #注册
    # url(r'^register/',views.my_register,name='my_register'),
    #上传新房源
    url(r'^addnewhouse/',views.my_new_house,name='my_new_house'),
    #房源添加后展示
    # url(r'^shownewhouse/',views.show_newhouse,name='show_new_house'),
    #成功添加房源后跳转页面
    url(r'^success/', views.show_success, name='show_success'),
    # url(r'^removenewhouse/',views.remove_newhouse,name='remove_newhouse')


]

project/app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Area(models.Model):
    area_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'area'

    def __str__(self):
        return self.name


class Collect(models.Model):
    user = models.ForeignKey('User', models.DO_NOTHING, primary_key=True)
    house = models.ForeignKey('House', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'collect'
        unique_together = (('user', 'house'),)

# class Collect(models.Model):
#     user = models.ForeignKey('User', models.DO_NOTHING, primary_key=True)
#     house = models.ForeignKey('House', models.DO_NOTHING)
#
#     class Meta:
#         managed = False
#         db_table = 'collect'
#         unique_together = (('user', 'house'),)


class Count(models.Model):
    count_id = models.AutoField(primary_key=True)
    house = models.ForeignKey('House', models.DO_NOTHING, blank=True, null=True)
    look_times = models.IntegerField(blank=True, null=True)
    area_look_times = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'count'


class House(models.Model):
    house_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('User', models.DO_NOTHING, blank=True, null=True)
    area = models.ForeignKey(Area, models.DO_NOTHING, blank=True, null=True)
    type = models.ForeignKey('HouseType', models.DO_NOTHING, blank=True, null=True)
    title = models.CharField(max_length=1024, blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    address = models.CharField(max_length=512, blank=True, null=True)
    acreage = models.IntegerField(blank=True, null=True)
    index_img_url = models.CharField(max_length=1024, blank=True, null=True)
    house_status = models.CharField(max_length=10, null=True)
    col_user = models.ManyToManyField('User', through='Collect', related_name='col_house')


    class Meta:
        managed = False
        db_table = 'house'


class Facility(models.Model):
    facility_id = models.AutoField(primary_key=True)
    facility_name = models.CharField(max_length=128, blank=True, null=True)
    css = models.CharField(max_length=512, blank=True, null=True)
    houses = models.ManyToManyField(House, through='HouseFacility')

    class Meta:
        managed = False
        db_table = 'facility'


class HouseFacility(models.Model):
    facility = models.ForeignKey(Facility, models.DO_NOTHING, primary_key=True)
    house = models.ForeignKey(House, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'house_facility'

        unique_together = (('facility', 'house'),)



class HouseDetail(models.Model):
    detail_id = models.AutoField(primary_key=True)
    house = models.ForeignKey(House, models.DO_NOTHING, blank=True, null=True)
    lease = models.CharField(max_length=512, blank=True, null=True)
    pay_way = models.CharField(max_length=512, blank=True, null=True)
    floor = models.CharField(max_length=512, blank=True, null=True)
    house_head = models.CharField(max_length=128, blank=True, null=True)
    community = models.CharField(max_length=512, blank=True, null=True)
    surround_facility = models.CharField(max_length=1024, blank=True, null=True)
    transportation = models.CharField(max_length=1024, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'house_detail'


class HouseImg(models.Model):
    img_id = models.AutoField(primary_key=True)
    house = models.ForeignKey(House, models.DO_NOTHING, blank=True, null=True)
    url = models.CharField(max_length=2048, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'house_img'


class HouseType(models.Model):
    type_id = models.AutoField(primary_key=True)
    type_name = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'house_type'

    def __str__(self):
        return self.type_name


class Role(models.Model):
    role_id = models.AutoField(primary_key=True)
    vip = models.IntegerField(blank=True, null=True)
    admin = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'role'


class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    role = models.ForeignKey(Role, models.DO_NOTHING, blank=True, null=True)
    account = models.CharField(unique=True, max_length=128, blank=True, null=True)
    password = models.CharField(max_length=128, blank=True, null=True)
    phone = models.CharField(max_length=128,blank=True, null=True)
    nick_name = models.CharField(max_length=128, blank=True, null=True)
    avatar = models.ImageField(upload_to='icon', blank=True, null=True)
    id_name = models.CharField(max_length=64, blank=True, null=True)
    id_card = models.CharField(max_length=64, blank=True, null=True)
    ticket = models.CharField(max_length=255, blank=True, null=True)
    out_time = models.DateTimeField()


    class Meta:
        managed = False
        db_table = 'user'


class Forbidden(models.Model):
    user = models.ForeignKey('User', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'forbidden'

project/detail/models.py
from django.db import models

# Create your models here.

project/detail/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from app.models import House, Facility, Collect, User
from django.core import exceptions


# Create your views here.

def detail(request, house_id):
    if request.method == 'GET':
        data = {}
        house = House.objects.filter(house_id=house_id)
        if house[0]:
            data['house'] = house[0]
            data['user'] = house[0].user
            data['house_type'] = house[0].type
            data['house_area'] = house[0].area
            data['house_detail'] = house[0].housedetail_set.first()
            data['house_img'] = house[0].houseimg_set.all()
            temp = [fac.facility_name for fac in house[0].facility_set.all()]
            data['fac'] = [(fac, bool(fac.facility_name in temp)) for fac in Facility.objects.all()]

        return render(request, 'detail.html', {'data': data})


def collect(request):
    if request.method == 'POST':
        house_id = request.POST.get('house_id')
        user_account = request.session.get('account')
        method = request.POST.get('method')
        house = House.objects.filter(house_id=house_id).first()
        if method == '1':
            if user_account:
                user = User.objects.filter(account=user_account).first()
                if Collect.objects.filter(user=user, house=house).exists():
                    return JsonResponse({'code': 1})
                else:
                    return JsonResponse({'code': 0})
            else:
                return JsonResponse({'code': 0})
        elif method == '2':
            if user_account:
                user = User.objects.filter(account=user_account).first()
                if Collect.objects.filter(user=user, house=house).exists():
                    return JsonResponse({'code': 0})
                else:
                    try:
                        Collect.objects.create(user=user, house=house)
                        return JsonResponse({'code': 1})
                    except exceptions:
                        return JsonResponse({'code':0})
            else:
                return JsonResponse({'code':5})
        elif method == '3':
            if user_account:
                user = User.objects.filter(account=user_account).first()
                if Collect.objects.filter(user=user, house=house).exists():
                    try:
                        Collect.objects.filter(user=user, house=house).delete()
                        return JsonResponse({'code': 1})
                    except exceptions:
                        return JsonResponse({'code': 0})
                else:
                    return JsonResponse({'code': 0})
            else:
                return JsonResponse({'code':5})

project/xym/views.py
import os

from django.contrib.auth import authenticate
from django.contrib.auth.backends import UserModel
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.sites import requests
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render

from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from app.models import Facility, Area, HouseType, House, User, HouseDetail, HouseImg, HouseFacility


# 用户登录
def login(request):
    if request.method == 'GET':
        return render(request, 'xym/login.html')

    # post请求获取信息
    if request.method == 'POST':
        username = request.POST.get('account')
        password = request.POST.get('password')

        if User.objects.filter(account=username).exists():
            users = User.objects.filter(account=username)

            # if check_password(password, users[0].password):
            if password == users[0].password:

                # 将登录的账户名传递给session对象
                request.session['account'] = username

                return HttpResponseRedirect('/xym/index.html')
            else:  # wrong password
                return HttpResponse('登录密码错误')
        else:  # wrong user
            return HttpResponse('登录账号错误')


# 上传新房源
@csrf_exempt
def my_new_house(request):
    username = request.session.get('account')
    users = User.objects.filter(account=username)
    user_id = users[0].user_id
    user_idcard = users[0].id_card


    if request.method == 'GET':
        #节约查询时间
        if user_id and user_idcard:
            area = Area.objects.all()
            facility_name = Facility.objects.all()
            facilitys_id = Facility.objects.all
            type_names = HouseType.objects.all()
            data = {
                'area': area,
                'facility_name': facility_name,
                'type_names': type_names,
                'facility_id': facilitys_id
            }

            # if the user is login
            return render(request, 'xym/newhouse.html', data)
        elif user_id:
            return HttpResponseRedirect('/cwd/ture/')
        else:
            # if not login return to login page
            return render(request, 'xym/login.html')

        area = Area.objects.all()
        facility_name = Facility.objects.all()
        facility_id = Facility.objects.all
        type_names = HouseType.objects.all()
        data = {
            'area': area,
            'facility_name': facility_name,
            'type_names': type_names,
            'facility_id': facility_id
        }
        return render(request, 'xym/newhouse.html', data)

    if request.method == 'POST':

        title = request.POST.get('title')
        # 价格
        price = request.POST.get('price')

        # 支付方式
        pay_way = request.POST.get('pay_way')

        # 租赁方式
        lease = request.POST.get('lease')
        # 区域
        area_id = request.POST.get('area_id')  # this is the name as in html under name=

        # 地址
        address = request.POST.get('address')
        # 面积
        acreage = request.POST.get('acreage')
        # 房型
        type = request.POST.get('type')
        type_id = 1

        # 楼层
        floor = request.POST.get('floor')
        # 朝向
        house_head = request.POST.get('house_head')
        # 小区名
        community = request.POST.get('community')
        # 周围设施
        surround_facility = request.POST.get('surround_facility')
        # 交通
        transportation = request.POST.get('transportation')
        # 获取House数据
        # house_form = House(data=request.POST)
        # 房屋图片
        img_file = request.FILES.get('house_image')
        # use the FileSystemStorage() function
        fs = FileSystemStorage()
        filename = fs.save(img_file.name, img_file)
        index_img_url = fs.url(filename)

        facilitys_id = request.POST.getlist('facilitys')  # get name from html

        # 房屋状态
        house_status = request.POST.get('house_statuss')

        # insert into the databases
        house = House.objects.create(
            # this creates new house in table, house id is automatically created for this object
            user_id=user_id,
            area_id=area_id,
            type_id=type_id,
            title=title,
            price=price,
            address=address,
            acreage=acreage,
            index_img_url=index_img_url,
            house_status=house_status

        )
        house_id = house.house_id
        house_detail = HouseDetail.objects.create(
            house_id=house_id,
            lease=lease,
            pay_way=pay_way,
            floor=floor,
            house_head=house_head,
            community=community,
            surround_facility=surround_facility,
            transportation=transportation

        )
        url = house.index_img_url
        img = HouseImg.objects.create(
            house_id=house_id,
            url=url

        )

        # for loop over facility_id to add lines to facility database
        for facility_id in facilitys_id:
            facility = HouseFacility.objects.create(

                house_id=house_id,
                facility_id=facility_id
            )

        return render(request, 'xym/success.html')




def show_success(request):
    if request.method == 'GET':
        return render(request, 'xym/success.html')

project/templates/xym/login.html
{% load static %}
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>首页</title>
<link rel="stylesheet" type="text/css" href="{% static '/xym/css/style.css' %}">
<!-- <link rel="stylesheet/less" type="text/css" href="css/style.less" /> -->
<script type="text/javascript" src="{% static '/xym/js/jquery-1.7.2.min.js' %}"></script>
<script type="text/javascript" src="{% static '/xym/js/all.js' %}"></script>
<!--[if IE 6]>
<script src="./js/iepng.js" type="text/javascript"></script>
<script type="text/javascript">
   EvPNG.fix('div, ul, img, li, input,span, p');
</script>
<![endif]-->
</head>
<body>
<!-- header start -->
<div class="zxcf_top_wper">
	<div class="zxcf_top px1000 clearfix">
		 <div class="zxcf_top_l fl">
		    <img src="images/zxcf_phone.png" alt="">
		    400-027-0101(工作时间9:00-17:30)
		    <a href="#"><img src="{% static '/xym/images/zxcf_weixin.png' %}" alt=""></a>
		    <a href="#"><img src="{% static '/xym/images/zxcf_sina.png' %}" alt=""></a>
		    <a href="#"><img src="{% static '/xym/images/zxcf_qq.png' %}" alt=""></a>
		 </div>
		 <div class="zxcf_top_r fr">
		 	<a href="login.html" class="curspan">立即登录</a>
		 	<span>|</span>
		 	<a href="register.html">免费注册</a>
		 	<span>|</span>
		 	<a href="problem.html">常见问题</a>
		 </div>
	</div>
</div>
<!-- end top -->
<div class="zxcf_nav_wper">
	<div class="zxcf_nav clearfix px1000">
		 <div class="zxcf_nav_l fl"><img src="{% static '/xym/images/zxcf_logo.png' %}" alt=""></div>
		 <div class="zxcf_nav_r fr">
		 		<img src="{% static '/xym/images/lg_pic01.png' %}" alt="">
		 	<span>
		    <a href="index.html">返回首页</a></span>

		 </div>
	</div>
</div>
<!-- end  -->
<div class="login_con_wper">
	  <div class="login_con px1000 ">
	  	   <div class="lg_section clearfix">
{#              <div class="'lg_section_1">#}
{#                   <img src="{% static '/xym/images/lg_bg02.png' %}" width="200">#}
{#              </div>#}

	  	   	     <!-- end l -->
	  	   	     <div class="lg_section_r fl">
	  	   	     	   <h2 class="lg_sec_tit clearfix">
	  	   	     	      <span class="fl">登录</span>
	  	   	     	      <em class="fr">没有帐号，<a href="#">立即注册</a></em>
	  	   	     	   </h2>
	  	   	     	   <form method="post" action="{% url 'xym:login' %}">
                           {% csrf_token %}
	  	   	     	   	    <fieldset>
	  	   	     	   	    	  <p class="mt20">
	  	   	     	   	    	  	 <input type="text" name= 'account' placeholder="用户名/手机" class="lg_input01 lg_input">
	  	   	     	   	    	  </p>
                                  <p class="mt20">
	  	   	     	   	    	  	 <input type="text" name='password' placeholder="密码" class="lg_input02 lg_input">
	  	   	     	   	    	  </p>
                                 <p class="clearfix lg_check"><span class="fl"><input type="checkbox">记住用户名</span><a href="#" class="fr">忘记密码？找回</a></p>
                                 <!--<p><a href="xym/index" class="lg_btn">立即登陆</a></p>-->
                                  <input type="submit" class="btn btn-success" value="立即登陆">
	  	   	     	   	    </fieldset>
	  	   	     	   </form>
	  	   	     </div>
	  	   </div>
	  </div>
</div>
<!-- footer start -->
<div class="zscf_aboutus_wper">
	  <div class="zscf_aboutus px1000 clearfix">
	  	    <div class="zscf_aboutus_l fl">
	  	    	   <ul class="zscf_aboutus_lul clearfix">
	  	    	   	  <li class="pt10"><a href="#"><img src="{% static '/xym/images/app.png' %}" alt=""></a>
	  	    	   	  </li>
	  	    	   	  <li>
	  	    	   	  <p class="pb20">服务热线</p>
	  	    	   	  <strong>400-027-0101</strong>
	  	    	   	  </li>
	  	    	   	  <li>
	  	    	   	  	  <p class="pb10 linkpic">
	  	    	   	  	     <a href="#"><img src="{% static '/xym/images/ft_sina.png' %}" alt=""></a>
	  	    	   	  	     <a href="#"><img src="{% static '/xym/images/ft_weixin.png' %}" alt=""></a>
	  	    	   	  	     <a href="#"><img src="{% static '/xym/images/ft_erji.png' %}" alt=""></a>
	  	    	   	  	  </p>
	  	    	   	  	  <p><a href="#">kefu@zhongxincaifu.com</a></p>
	  	    	   	  </li>
	  	    	   </ul>
	  	    </div>
	  	    <!-- end left -->
	  	    <div class="zscf_aboutus_r fl clearfix">
	  	    	 <a href="#" class="fl ft_ewm"><img src="{% static '/xym/images/ft_erweima.png' %}" alt=""></a>
	  	    	 <ul class="fl clearfix">
	  	    	 	<li><a href="#">联系我们</a></li>
	  	    	 	<li><a href="#">我要租房</a></li>
	  	    	 	<li><a href="problem.html">帮助中心</a></li>
	  	    	 	<li><a href="#">友情链接</a></li>
	  	    	 	<li><a href="#">招贤纳士</a></li>
	  	    	 	<li><a href="#">更多</a></li>
	  	    	 </ul>
	  	    </div>
	  	    <!-- end right -->

	  </div>
</div>

<div class="zscf_bottom_wper">
	<div class="zscf_bottom px1000 clearfix">
		  <p class="fl">© 2014 zhongxincaifu &nbsp;  &nbsp;&nbsp;   东陵才俊房源股份有限公司</p>
		  <p class="fr">
		    <a href="#"><img src="{% static '/xym/images/360.png' %}" alt=""></a>
		    <a href="#"><img src="{% static '/xym/images/kexin.png' %}" alt=""></a>
		    <a href="#"><img src="{% static '/xym/images/norton.png' %}" alt=""></a>
		  </p>
	</div>

</div>
<!-- footer end -->
</body>
</html>

project/templates/xym/picture.html
<!DOCTYPE html>
<html>
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家-个人信息</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/main.css" rel="stylesheet">
    <link href="/static/css/profile.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">上传房屋照片</h3>
                <a class="nav-btn fl" href="/user/my/"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="menus-con">
            <ul class="menus-list">
                <li>
                    <div class="menu-title">
                        <h3>房屋图片信息</h3>
                    </div>
                    <div class="menu-content">
                        <img id="user-avatar" src="">
                        <div class="menu-text">
                            <form id="form-avatar" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                选择照片：<input type="file" accept="image/*" name="avatar">
                                <input type="submit" class="btn btn-success" value="上传">

                            </form>
                             <form id="form-name" action="" method="POST">
                                 {% csrf_token %}
{#                            <input type="text" name="name" id="user-name">#}
                            <input type="submit" class="btn btn-success" value="保存">
                        </form>
                        </div> 
                    </div>
                </li>
                <li>

{#                        <form id="form-name" action="" method="">#}
{#                            <input type="text" name="name" id="user-name">#}
{#                            <input type="submit" class="btn btn-success" value="保存">#}
{#                        </form>#}
                        <div class="error-msg"></div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="popup_con">
{#            <div class="popup">#}
{#                <p>保存成功！</p>#}
{#            </div>#}
            
            <div class="mask"></div>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>东陵租房&nbsp;&nbsp;享受家的温馨</p>
        </div> 
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/jquery.form.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/profile.js"></script>
</body>
</html>

project/templates/xym/showHouse.html
{% extends 'basr_my_min.html' %}
{% load static %}
{% block CSS %}
    <script type="text/javascript">
        $(function () {
            $(".leftnav h2").click(function () {
                $(this).next().slideToggle(200);
                $(this).toggleClass("on");
            })
            $(".leftnav ul li a").click(function () {
                $("#a_leader_txt").text($(this).text());
                $(".leftnav ul li a").removeClass("on");
                $(this).addClass("on");
            })
        });
    </script>
{% endblock %}
{% block content %}


    <div class="admin">
        <div class="panel admin-panel">
            <div class="panel-head"><strong class="icon-reorder"> 已发布的房源</strong></div>
            <div class="padding border-bottom">
            </div>
            <table class="table table-hover text-center">
                {% if user %}
                    <tr>
                        <th width="10%">房屋ID</th>
                        <th width="10%">图片</th>
                        <th width="20%">标题</th>
                        <th width="10%">价格</th>
                        <th width="10%">区域</th>
                        <th width="10%">地址</th>
{#                        <th width="10%">房屋设施</th>#}
                        <th width="10%">房屋状态</th>

                        <th width="10%">操作</th>
                    </tr>
                    {% for h in house %}


                        <tr>
                            <td>{{ h.house_id }}</td>
                            <td><img src="{{ h.index_img_url }}" alt="" width="120" height="50"/></td>
                            <td>{{ h.title }}</td>
                            <td>{{ h.price }}</td>
                            <td>{{ h.area }}</td>
                            <td>{{ h.address }}</td>
{#                            <td>{{ h.housefacility_set }}</td>#}
                            <td>{{ h.house_status }}</td>

                            <td>
                                <div class="button-group">
                                    <a class="button border-red" href="javascript:void(0)"
                                       onclick="return del({{ h.house_id }})"><span
                                            class="icon-trash-o"></span> 删除</a>

                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
        </div>
        <script type="text/javascript">
            function del(id) {
                var r = confirm("您确定要删除吗?")
                if (r == true) {
                    alert("You pressed OK!");
                    $.post( "/xym/removenewhouse/", { house_id: id, csrfmiddlewaretoken: '{{ csrf_token }}' } ); // send data to server django: js -> urls.py -> views.py
                }
                else {
                    alert("You pressed Cancel!");
                }
            }
        </script>
    </div>
{% endblock %}

project/templates/xym/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>添加成功！</h1>
<a href="/xym/shownewhouse">返回</a>
</body>
</html>